apiVersion: v1
kind: Pod
metadata:
  name: demo-kotlin-app
  labels:
    role: webapp
spec:
  containers:
  - name: web
    image: rtmabiola/demo-kotlin1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        name: web
        protocol: TCP