name: 'Terraform'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: 'Install pre-reqs'
      run: |
        curl -SL "https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip" --output terraform.zip
        unzip "terraform.zip"
        mv terraform /usr/local/bin
        terraform --version
        rm terraform.zip
      
    - name: 'Install TFLint'
      run: |
        wget https://github.com/terraform-linters/tflint/releases/download/v0.44.1/tflint_linux_amd64.zip
        unzip tflint_linux_amd64
        mv tflint /usr/local/bin

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform plan
      run: terraform plan